name: Build Notebooks

on:
  push:
    branches: [ "**" ]
    paths: 
      - "examples/**"
      - "docs/postprocess.py"
      - ".github/workflows/run_notebooks.yml"
  pull_request:
    branches: [ main ]
    paths: 
      - "examples/**"
      - "docs/postprocess.py"
      - ".github/workflows/run_notebooks.yml"

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Cache StarSim data
        uses: actions/cache@v4
        with:
          path: ~/.starsim/cache
          key: starsim-cache-v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]

      - name: Execute notebook
        run: |
          jupyter nbconvert --to html --execute examples/osiris-rex.ipynb --output ./osiris-rex.html
          touch docs/.nojekyll
          python docs/postprocess.py

      - name: Upload notebook artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebooks
          path: examples/*.html