name: Unit Tests

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - "data/**"
      - "docs/**"
      - "examples/**"
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - "data/**"
      - "docs/**"
      - "examples/**"

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
          coverage xml
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5